spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farmbroker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: nick0715!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api

jwt:
  secret: 12341234123412341234123412341234
  expiration: 86400000